version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://root:example@mongo:27017/auth
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command: npm start

  profile-service:
    build:
      context: ./services/profile-service
    container_name: profile-service
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://root:example@mongo:27017/profile?authSource=admin
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    command: npm start
